import Link from "next/link";
import "./globals.css";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: {
        template: "%s | Next.js",
        default: "Next.js | Routing Demo",

    },
    description: "Generated by create next app",
}
export default function RootLayout({ children }: { children: React.ReactNode }) {
    return <html lang="en">
        <head>
            <title>Routing Demo</title>
        </head>
        <body>
            <header>
                <nav>
                    <ul className="flex gap-4 bg-slate-600 text-white p-4">
                        <li><Link href="/">Home</Link></li>
                        <li><Link href="/about">About</Link></li>
                        <li><Link href="/counter">Counter</Link></li>
                        <li><Link href="/blog">Blog</Link></li>
                        <li><Link href="/products">Products</Link></li>
                        <li><Link href="/docs">Docs</Link></li>
                        <li><Link href="/login">Login</Link></li>
                        <li><Link href="/register">Register</Link></li>
                        <li><Link href="/forgot-password">Forgot Password</Link></li>
                        <li><Link href="/profile">Profile</Link></li>
                        <li><Link href="/private-route">Private Route</Link></li>
                        <li><Link href="/_underscore-route">Underscore Route</Link></li>
                    </ul>
                </nav>
            </header>
            {children}
            <footer className="flex bg-slate-600 justify-center p-4 text-white">
                <p>Footer</p>
            </footer>
            </body>
    </html>;
}