import "./globals.css";
import { Metadata } from "next";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
    title: {
        template: "%s | Next.js",
        default: "Next.js | Routing Demo",

    },
    description: "Generated by create next app",
}
export default function RootLayout({ children }: { children: React.ReactNode }) {
    return <html lang="en">
        <head>
            <title>Routing Demo</title>
        </head>
        <body className="flex flex-col min-h-screen">
            <header>
                <Navbar />
            </header>
            <main className="flex-1 items-center justify-center">
            {children}
            </main>
            <footer className="flex bg-slate-600 justify-center p-4 text-white">
                <p>Footer</p>
            </footer>
        </body>
    </html>;
}